---
title: "Estudio de microarrays PEC1"
author: "Sandra Bernaus Tomé"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Download GEO data
```{r }
if (!require(GEOquery)) {
  BiocManager::install("GEOquery")
}
require(GEOquery)
gse <- getGEO("GSE2401")
class(gse)
names(gse)
gse[[1]]
esetFromGEO<-gse[[1]]
class(esetFromGEO)
```


### Whats in the data

```{r}
head(exprs(esetFromGEO))
description(esetFromGEO)
abstract(esetFromGEO)
pData(esetFromGEO)$description
pData(esetFromGEO)
```
## Control de calidad/normalidad
```{r}
library(arrayQualityMetrics)
arrayQualityMetrics(esetFromGEO)
```
```{r}
library(ggplot2)
library(ggrepel)
plotPCA3 <- function (datos, labels, factor, title, scale,colores, size = 1.5, glineas = 0.25) {
  data <- prcomp(t(datos),scale=scale)
  # plot adjustments
  dataDf <- data.frame(data$x)
  Group <- factor
  loads <- round(data$sdev^2/sum(data$sdev^2)*100,1)
 # main plot
  p1 <- ggplot(dataDf,aes(x=PC1, y=PC2)) +
    theme_classic() +
    geom_hline(yintercept = 0, color = "gray70") +
    geom_vline(xintercept = 0, color = "gray70") +
    geom_point(aes(color = Group), alpha = 0.55, size = 3) +
    coord_cartesian(xlim = c(min(data$x[,1])-5,max(data$x[,1])+5)) +
    scale_fill_discrete(name = "Group")
   # avoiding labels superposition
   p1 + geom_text_repel(aes(y = PC2 + 0.25, label = labels),segment.size = 0.25, size = size) + 
     labs(x = c(paste("PC1",loads[1],"%")),y=c(paste("PC2",loads[2],"%"))) +  
     ggtitle(paste("Principal Component Analysis for: ",title,sep=" "))+ 
     theme(plot.title = element_text(hjust = 0.5)) +
     scale_color_manual(values=colores)
   }
```

```{r}
plotPCA3(exprs(esetFromGEO), labels =(colnames(exprs(esetFromGEO))), factor = pData(esetFromGEO)$description, ##esta mal
          title="Raw data", scale = FALSE, size = 3, 
          colores = c("red", "blue", "green", "yellow"))
```